name: github-kafka-demo

volumes:
  clickhouse_data: {}
  clickhouse_logs: {}
  grafana_storage: {}


services:
  broker:
    image: apache/kafka:latest
    hostname: broker
    container_name: broker
    ports:
      - 9092:9092     # Expose external port
    environment:
      KAFKA_BROKER_ID: 1
      # Map listener names to security protocols (no auth)
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      # Define what addresses to advertise to clients
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker:29092,EXTERNAL://localhost:9092
      # Basic Kafka configs
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      # KRaft mode settings
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      # Define interfaces and ports to listen on
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://broker:29093
      # Internal communication between brokers (if you had multiple)
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

  clickhouse-server:
    image: clickhouse/clickhouse-server:25.4
    container_name: clickhouse-server
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
    ports:
      - "8123:8123"   # HTTP interface
      - "9000:9000"   # Native TCP interface
      - "9009:9009"   # Interserver communication port
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=ClickHousePassword
      - CLICKHOUSE_DB=default
  
  grafana:
    depends_on:
      - broker
    container_name: grafana
    env_file:
      - environment
    image: grafana/grafana:${GRAFANA_VERSION:-10.4.3}
    volumes:
      - grafana_storage:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - 3000:3000
    restart: on-failure
    user: root
  
  # githubeventsproducer:
  #   build:
  #     context: ./githubeventsproducer/.
  #     dockerfile: Dockerfile
  #   container_name: githubeventsproducer
  #   depends_on:
  #     - kafka-broker
  #   volumes:
  #     - ./githubeventsproducer:/opt/app
  #   working_dir: /opt/app
